version: '3'

services:
  web:
    build:
      context: webapp
      dockerfile: Dockerfile
    image: proffapt/scmb-web
    container_name: scmb-web
    env_file:
      - .env 
    volumes:
      - ./webapp/certificates:/app/certificates
    ports:
      - 80:8000
    networks:
      - scmb-network

  db:
    build:
      context: postgres
      dockerfile: Dockerfile
    image: proffapt/scmb-db
    container_name: scmb-db
    env_file:
      - .env 
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - scmb-network

volumes:
  data:

networks:
  scmb-network:
    driver: bridge 
